version: '3.7'

services:
  sgtm-server:
    image: moul/sgtm:latest
    restart: on-failure
    volumes:
      - .:/app
      - "/etc/localtime:/etc/localtime:ro"
    working_dir: /app
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    command: |
      --enable-server
      --ipfs-api /dns4/ipfs-daemon/tcp/5001
      run
    ports:
      - 8000
    environment:
      - VIRTUAL_HOST=sgtm.club
      - LETSENCRYPT_HOST=sgtm.club
      - VIRTUAL_PORT=8000
    networks:
      - default
      - ipfs
      - service-proxy

  sgtm-discord:
    image: moul/sgtm:latest
    restart: on-failure
    volumes:
      - .:/app
    working_dir: /app
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    command: --enable-discord run
    networks:
      - default

  ipfs-daemon:
    image: ipfs/go-ipfs:latest
    restart: on-failure
    volumes:
      - ./ipfs/export:/export
      - ./ipfs/data:/data/ipfs
    ports:
      - 4001:4001
      - 4001:4001/udp
    networks:
      - ipfs

networks:
  service-proxy:
    external: true
  ipfs:
